### ISSUE TITLE
Form field and vocabulary changes

### ISSUE THREAD

**Issue by zachsa** [SAEON/national-climate-change-systems#20]
- [x] Change "Implementation status" vocabulary (Web)
- [x] Change "Implementation status" vocabulary (Excel)

Planned => Planned
Operational => Under implementation
Discontinued => Project Ended
Completed => Completed

(Also, change description to match the new vocabulary)

- [x] Change "Mitigation units" vocabulary (Web)
- [x] Change "Mitigation units" vocabulary (Excel)

kWh (total energy savings)
kWh (Power generated)
MW installed capacity (Installed capacity)
MJ (Fuel consumption)
tons of waste reduced
tons of waste reused
tons of waste recycled

- [x] New term in 'fundingType' (Web) => `other`
- [x] New term in 'fundingType' (Excel) => `other`
- [x] New field for fundingType 'otherDescription' (Web)
- [x] New field for fundingType 'otherDescription' (Excel)

- [x] Provinces list should include 'National'. This needs to be changed on the Excel template

- [x] Change 'validationStatus' to 'submissionStatus'

- [x] National and regional policies should be multiselect (Web)
- [x] National and regional policies should be multiselect (Excel)

- [x] Hazards should be multiselect (Web)
- [x] Hazards should be multiselect (Excel)

- [x] New field (web): "otherImplementingPartners"
- [x] New field (Excel): "otherImplementingPartners"

- [x] Add CDM number to Excel form (already on online form)

**Comment by Dmathevula** [comment]
Hi Zach ....

**Comment by zachsa** [comment]
Hi @Dmathevula - welcome to the GitHub issues tracker!

There is actually one thing I'm still waiting on the DFFE for - please can you confirm the required fields for mitigation and adaptation details: https://github.com/SAEON/national-climate-change-systems/issues/21

**Comment by zachsa** [comment]
Done
