### ISSUE TITLE
Download projects

### ISSUE THREAD

**Issue by clairedavis-reddy** [SAEON/national-climate-change-systems#36]
A public user needs to be able to download all projects in the database. This was a feature in the previous version of NCCRD and DFFE has requested it to be added to the new version.

**Comment by zachsa** [comment]
This is related to the Excel sheet - users will be able to download all data into an excel sheet, and then reupload with changes

**Comment by clairedavis-reddy** [comment]
So they will be able to download every project in the database?

Is this a to-do feature?

**Comment by zachsa** [comment]
yes - not implemented yet.

come to think about it... being able to update every project in the database via an excel sheet doesn't sound like a good idea. updates will be limited to the web form. but users will be able to download every project

**Comment by clairedavis-reddy** [comment]
Can there be an easily accessible button to "Download All"? This functionality was in the previous NCCRD.

**Comment by zachsa** [comment]
Yes

**Comment by zachsa** [comment]
@clairedavis-reddy - this features has been implemented as a CSV download
